# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stackedVDGame.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 699)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 204, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 204, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 204, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 204, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.VirtualDayExp = QtWidgets.QStackedWidget(self.centralwidget)
        self.VirtualDayExp.setGeometry(QtCore.QRect(10, -10, 1421, 861))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 204, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 204, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 204, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 204, 102))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.VirtualDayExp.setPalette(palette)
        self.VirtualDayExp.setAutoFillBackground(False)
        self.VirtualDayExp.setObjectName("VirtualDayExp")
        self.ConsentPage = QtWidgets.QWidget()
        self.ConsentPage.setAutoFillBackground(True)
        self.ConsentPage.setObjectName("ConsentPage")
        self.consentHeader = QtWidgets.QLabel(self.ConsentPage)
        self.consentHeader.setGeometry(QtCore.QRect(250, 210, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(18)
        self.consentHeader.setFont(font)
        self.consentHeader.setObjectName("consentHeader")
        self.banner2 = QtWidgets.QLabel(self.ConsentPage)
        self.banner2.setGeometry(QtCore.QRect(510, 10, 451, 121))
        self.banner2.setText("")
        self.banner2.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner2.setObjectName("banner2")
        self.partID = QtWidgets.QLineEdit(self.ConsentPage)
        self.partID.setGeometry(QtCore.QRect(290, 270, 161, 21))
        self.partID.setObjectName("partID")
        self.errorConsent = QtWidgets.QLabel(self.ConsentPage)
        self.errorConsent.setGeometry(QtCore.QRect(250, 550, 451, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(141, 0, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 0, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.errorConsent.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.errorConsent.setFont(font)
        self.errorConsent.setToolTipDuration(0)
        self.errorConsent.setObjectName("errorConsent")
        self.banner1 = QtWidgets.QLabel(self.ConsentPage)
        self.banner1.setGeometry(QtCore.QRect(40, 10, 471, 121))
        self.banner1.setText("")
        self.banner1.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner1.setScaledContents(True)
        self.banner1.setObjectName("banner1")
        self.consentBody = QtWidgets.QTextBrowser(self.ConsentPage)
        self.consentBody.setGeometry(QtCore.QRect(280, 310, 371, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 173, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.consentBody.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.consentBody.setFont(font)
        self.consentBody.setObjectName("consentBody")
        self.directions = QtWidgets.QLabel(self.ConsentPage)
        self.directions.setGeometry(QtCore.QRect(290, 250, 271, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.directions.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.directions.setFont(font)
        self.directions.setObjectName("directions")
        self.submitConsent = QtWidgets.QPushButton(self.ConsentPage)
        self.submitConsent.setGeometry(QtCore.QRect(310, 490, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setBold(False)
        font.setWeight(50)
        self.submitConsent.setFont(font)
        self.submitConsent.setObjectName("submitConsent")
        self.consentBox = QtWidgets.QCheckBox(self.ConsentPage)
        self.consentBox.setGeometry(QtCore.QRect(280, 430, 351, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.consentBox.setFont(font)
        self.consentBox.setObjectName("consentBox")
        self.VirtualDayExp.addWidget(self.ConsentPage)
        self.demoPage = QtWidgets.QWidget()
        self.demoPage.setAutoFillBackground(True)
        self.demoPage.setObjectName("demoPage")
        self.genderLabel = QtWidgets.QLabel(self.demoPage)
        self.genderLabel.setGeometry(QtCore.QRect(240, 280, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.submitButton = QtWidgets.QPushButton(self.demoPage)
        self.submitButton.setGeometry(QtCore.QRect(300, 480, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")
        self.errorAge = QtWidgets.QLabel(self.demoPage)
        self.errorAge.setGeometry(QtCore.QRect(420, 430, 311, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(141, 0, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 0, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.errorAge.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.errorAge.setFont(font)
        self.errorAge.setToolTipDuration(0)
        self.errorAge.setObjectName("errorAge")
        self.Height = QtWidgets.QSpinBox(self.demoPage)
        self.Height.setGeometry(QtCore.QRect(300, 340, 61, 24))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.Height.setFont(font)
        self.Height.setObjectName("Height")
        self.banner3 = QtWidgets.QLabel(self.demoPage)
        self.banner3.setGeometry(QtCore.QRect(40, 10, 471, 121))
        self.banner3.setText("")
        self.banner3.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner3.setScaledContents(True)
        self.banner3.setObjectName("banner3")
        self.genderGroup = QtWidgets.QGroupBox(self.demoPage)
        self.genderGroup.setGeometry(QtCore.QRect(300, 239, 51, 91))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.genderGroup.setFont(font)
        self.genderGroup.setTitle("")
        self.genderGroup.setObjectName("genderGroup")
        self.Male = QtWidgets.QRadioButton(self.genderGroup)
        self.Male.setGeometry(QtCore.QRect(10, 0, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.Male.setFont(font)
        self.Male.setObjectName("Male")
        self.Female = QtWidgets.QRadioButton(self.genderGroup)
        self.Female.setGeometry(QtCore.QRect(10, 30, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.Female.setFont(font)
        self.Female.setObjectName("Female")
        self.Other = QtWidgets.QRadioButton(self.genderGroup)
        self.Other.setGeometry(QtCore.QRect(10, 60, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.Other.setFont(font)
        self.Other.setObjectName("Other")
        self.banner4 = QtWidgets.QLabel(self.demoPage)
        self.banner4.setGeometry(QtCore.QRect(510, 10, 451, 121))
        self.banner4.setText("")
        self.banner4.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner4.setObjectName("banner4")
        self.demoHeader = QtWidgets.QLabel(self.demoPage)
        self.demoHeader.setGeometry(QtCore.QRect(260, 210, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(18)
        self.demoHeader.setFont(font)
        self.demoHeader.setObjectName("demoHeader")
        self.errorDemo = QtWidgets.QLabel(self.demoPage)
        self.errorDemo.setGeometry(QtCore.QRect(300, 520, 441, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(141, 0, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 0, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.errorDemo.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.errorDemo.setFont(font)
        self.errorDemo.setToolTipDuration(0)
        self.errorDemo.setObjectName("errorDemo")
        self.heightLabel = QtWidgets.QLabel(self.demoPage)
        self.heightLabel.setGeometry(QtCore.QRect(210, 340, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.heightLabel.setFont(font)
        self.heightLabel.setObjectName("heightLabel")
        self.ageLabel = QtWidgets.QLabel(self.demoPage)
        self.ageLabel.setGeometry(QtCore.QRect(260, 420, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.weightLabel = QtWidgets.QLabel(self.demoPage)
        self.weightLabel.setGeometry(QtCore.QRect(200, 380, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.weightLabel.setFont(font)
        self.weightLabel.setObjectName("weightLabel")
        self.Age = QtWidgets.QSpinBox(self.demoPage)
        self.Age.setGeometry(QtCore.QRect(300, 420, 61, 24))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.Age.setFont(font)
        self.Age.setObjectName("Age")
        self.Weight = QtWidgets.QSpinBox(self.demoPage)
        self.Weight.setGeometry(QtCore.QRect(300, 380, 61, 24))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.Weight.setFont(font)
        self.Weight.setMaximum(999)
        self.Weight.setObjectName("Weight")
        self.VirtualDayExp.addWidget(self.demoPage)
        self.CAGE = QtWidgets.QWidget()
        self.CAGE.setObjectName("CAGE")
        self.CAGEdir_5 = QtWidgets.QLabel(self.CAGE)
        self.CAGEdir_5.setGeometry(QtCore.QRect(160, 500, 731, 16))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.CAGEdir_5.setFont(font)
        self.CAGEdir_5.setObjectName("CAGEdir_5")
        self.CAGEdir_2 = QtWidgets.QLabel(self.CAGE)
        self.CAGEdir_2.setGeometry(QtCore.QRect(160, 290, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.CAGEdir_2.setFont(font)
        self.CAGEdir_2.setObjectName("CAGEdir_2")
        self.submitButton_2 = QtWidgets.QPushButton(self.CAGE)
        self.submitButton_2.setGeometry(QtCore.QRect(580, 570, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.submitButton_2.setFont(font)
        self.submitButton_2.setObjectName("submitButton_2")
        self.CAGEdir = QtWidgets.QLabel(self.CAGE)
        self.CAGEdir.setGeometry(QtCore.QRect(220, 240, 441, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(71, 71, 71))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.CAGEdir.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.CAGEdir.setFont(font)
        self.CAGEdir.setObjectName("CAGEdir")
        self.CAGEBox1_4 = QtWidgets.QGroupBox(self.CAGE)
        self.CAGEBox1_4.setGeometry(QtCore.QRect(190, 450, 121, 41))
        self.CAGEBox1_4.setTitle("")
        self.CAGEBox1_4.setObjectName("CAGEBox1_4")
        self.Y3 = QtWidgets.QRadioButton(self.CAGEBox1_4)
        self.Y3.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.Y3.setObjectName("Y3")
        self.N3 = QtWidgets.QRadioButton(self.CAGEBox1_4)
        self.N3.setGeometry(QtCore.QRect(70, 10, 41, 20))
        self.N3.setObjectName("N3")
        self.CAGEHeader = QtWidgets.QLabel(self.CAGE)
        self.CAGEHeader.setGeometry(QtCore.QRect(220, 210, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(18)
        self.CAGEHeader.setFont(font)
        self.CAGEHeader.setObjectName("CAGEHeader")
        self.banner6 = QtWidgets.QLabel(self.CAGE)
        self.banner6.setGeometry(QtCore.QRect(510, 10, 451, 121))
        self.banner6.setText("")
        self.banner6.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner6.setObjectName("banner6")
        self.errorCAGE = QtWidgets.QLabel(self.CAGE)
        self.errorCAGE.setGeometry(QtCore.QRect(490, 610, 201, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(141, 0, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 0, 11))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.errorCAGE.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.errorCAGE.setFont(font)
        self.errorCAGE.setToolTipDuration(0)
        self.errorCAGE.setObjectName("errorCAGE")
        self.CAGEdir_3 = QtWidgets.QLabel(self.CAGE)
        self.CAGEdir_3.setGeometry(QtCore.QRect(160, 360, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.CAGEdir_3.setFont(font)
        self.CAGEdir_3.setObjectName("CAGEdir_3")
        self.banner5 = QtWidgets.QLabel(self.CAGE)
        self.banner5.setGeometry(QtCore.QRect(40, 10, 471, 121))
        self.banner5.setText("")
        self.banner5.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner5.setScaledContents(True)
        self.banner5.setObjectName("banner5")
        self.CAGEBox1_2 = QtWidgets.QGroupBox(self.CAGE)
        self.CAGEBox1_2.setGeometry(QtCore.QRect(190, 310, 121, 41))
        self.CAGEBox1_2.setTitle("")
        self.CAGEBox1_2.setObjectName("CAGEBox1_2")
        self.Y1 = QtWidgets.QRadioButton(self.CAGEBox1_2)
        self.Y1.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.Y1.setObjectName("Y1")
        self.N1 = QtWidgets.QRadioButton(self.CAGEBox1_2)
        self.N1.setGeometry(QtCore.QRect(70, 10, 41, 20))
        self.N1.setObjectName("N1")
        self.CAGEBox1_3 = QtWidgets.QGroupBox(self.CAGE)
        self.CAGEBox1_3.setGeometry(QtCore.QRect(190, 380, 121, 41))
        self.CAGEBox1_3.setTitle("")
        self.CAGEBox1_3.setObjectName("CAGEBox1_3")
        self.Y2 = QtWidgets.QRadioButton(self.CAGEBox1_3)
        self.Y2.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.Y2.setObjectName("Y2")
        self.N2 = QtWidgets.QRadioButton(self.CAGEBox1_3)
        self.N2.setGeometry(QtCore.QRect(70, 10, 41, 20))
        self.N2.setObjectName("N2")
        self.CAGEdir_4 = QtWidgets.QLabel(self.CAGE)
        self.CAGEdir_4.setGeometry(QtCore.QRect(160, 430, 441, 16))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.CAGEdir_4.setFont(font)
        self.CAGEdir_4.setObjectName("CAGEdir_4")
        self.CAGEBox1 = QtWidgets.QGroupBox(self.CAGE)
        self.CAGEBox1.setGeometry(QtCore.QRect(190, 520, 121, 41))
        self.CAGEBox1.setTitle("")
        self.CAGEBox1.setObjectName("CAGEBox1")
        self.Y4 = QtWidgets.QRadioButton(self.CAGEBox1)
        self.Y4.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.Y4.setObjectName("Y4")
        self.N4 = QtWidgets.QRadioButton(self.CAGEBox1)
        self.N4.setGeometry(QtCore.QRect(70, 10, 41, 20))
        self.N4.setObjectName("N4")
        self.VirtualDayExp.addWidget(self.CAGE)
        self.instructionsPage = QtWidgets.QWidget()
        self.instructionsPage.setObjectName("instructionsPage")
        self.InstructionsHeader = QtWidgets.QLabel(self.instructionsPage)
        self.InstructionsHeader.setGeometry(QtCore.QRect(220, 210, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(18)
        self.InstructionsHeader.setFont(font)
        self.InstructionsHeader.setObjectName("InstructionsHeader")
        self.banner7 = QtWidgets.QLabel(self.instructionsPage)
        self.banner7.setGeometry(QtCore.QRect(40, 10, 471, 121))
        self.banner7.setText("")
        self.banner7.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner7.setScaledContents(True)
        self.banner7.setObjectName("banner7")
        self.banner8 = QtWidgets.QLabel(self.instructionsPage)
        self.banner8.setGeometry(QtCore.QRect(510, 10, 451, 121))
        self.banner8.setText("")
        self.banner8.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner8.setObjectName("banner8")
        self.OKButton = QtWidgets.QPushButton(self.instructionsPage)
        self.OKButton.setGeometry(QtCore.QRect(730, 550, 113, 32))
        self.OKButton.setObjectName("OKButton")
        self.label = QtWidgets.QLabel(self.instructionsPage)
        self.label.setGeometry(QtCore.QRect(220, 230, 601, 331))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.VirtualDayExp.addWidget(self.instructionsPage)
        self.gamePage = QtWidgets.QWidget()
        self.gamePage.setObjectName("gamePage")
        self.tile25 = QtWidgets.QLabel(self.gamePage)
        self.tile25.setGeometry(QtCore.QRect(410, 160, 31, 31))
        self.tile25.setText("")
        self.tile25.setPixmap(QtGui.QPixmap("event tile.png"))
        self.tile25.setScaledContents(True)
        self.tile25.setObjectName("tile25")
        self.tile35 = QtWidgets.QLabel(self.gamePage)
        self.tile35.setGeometry(QtCore.QRect(710, 160, 31, 31))
        self.tile35.setText("")
        self.tile35.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile35.setScaledContents(True)
        self.tile35.setObjectName("tile35")
        self.tile33 = QtWidgets.QLabel(self.gamePage)
        self.tile33.setGeometry(QtCore.QRect(650, 160, 31, 31))
        self.tile33.setText("")
        self.tile33.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile33.setScaledContents(True)
        self.tile33.setObjectName("tile33")
        self.banner10 = QtWidgets.QLabel(self.gamePage)
        self.banner10.setGeometry(QtCore.QRect(510, 10, 451, 121))
        self.banner10.setText("")
        self.banner10.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner10.setObjectName("banner10")
        self.tile27 = QtWidgets.QLabel(self.gamePage)
        self.tile27.setGeometry(QtCore.QRect(470, 160, 31, 31))
        self.tile27.setText("")
        self.tile27.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile27.setScaledContents(True)
        self.tile27.setObjectName("tile27")
        self.Timer = QtWidgets.QLabel(self.gamePage)
        self.Timer.setGeometry(QtCore.QRect(510, 390, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.Timer.setFont(font)
        self.Timer.setAlignment(QtCore.Qt.AlignCenter)
        self.Timer.setObjectName("Timer")
        self.tile26 = QtWidgets.QLabel(self.gamePage)
        self.tile26.setGeometry(QtCore.QRect(440, 160, 31, 31))
        self.tile26.setText("")
        self.tile26.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile26.setScaledContents(True)
        self.tile26.setObjectName("tile26")
        self.tile4 = QtWidgets.QLabel(self.gamePage)
        self.tile4.setGeometry(QtCore.QRect(620, 520, 31, 31))
        self.tile4.setText("")
        self.tile4.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile4.setScaledContents(True)
        self.tile4.setObjectName("tile4")
        self.tile47 = QtWidgets.QLabel(self.gamePage)
        self.tile47.setGeometry(QtCore.QRect(770, 460, 31, 31))
        self.tile47.setText("")
        self.tile47.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile47.setScaledContents(True)
        self.tile47.setObjectName("tile47")
        self.tile18 = QtWidgets.QLabel(self.gamePage)
        self.tile18.setGeometry(QtCore.QRect(380, 340, 31, 31))
        self.tile18.setText("")
        self.tile18.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile18.setScaledContents(True)
        self.tile18.setObjectName("tile18")
        self.tile30 = QtWidgets.QLabel(self.gamePage)
        self.tile30.setGeometry(QtCore.QRect(560, 160, 31, 31))
        self.tile30.setText("")
        self.tile30.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile30.setScaledContents(True)
        self.tile30.setObjectName("tile30")
        self.tile22 = QtWidgets.QLabel(self.gamePage)
        self.tile22.setGeometry(QtCore.QRect(380, 220, 31, 31))
        self.tile22.setText("")
        self.tile22.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile22.setScaledContents(True)
        self.tile22.setObjectName("tile22")
        self.tile1 = QtWidgets.QLabel(self.gamePage)
        self.tile1.setGeometry(QtCore.QRect(710, 520, 31, 31))
        self.tile1.setText("")
        self.tile1.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile1.setScaledContents(True)
        self.tile1.setObjectName("tile1")
        self.performTask = QtWidgets.QPushButton(self.gamePage)
        self.performTask.setGeometry(QtCore.QRect(640, 200, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.performTask.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.performTask.setFont(font)
        self.performTask.setAutoFillBackground(False)
        self.performTask.setStyleSheet("#performTask {\n"
"background-color: rgb(191, 143, 255)\n"
"}")
        self.performTask.setObjectName("performTask")
        self.tile20 = QtWidgets.QLabel(self.gamePage)
        self.tile20.setGeometry(QtCore.QRect(380, 280, 31, 31))
        self.tile20.setText("")
        self.tile20.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile20.setScaledContents(True)
        self.tile20.setObjectName("tile20")
        self.tile17 = QtWidgets.QLabel(self.gamePage)
        self.tile17.setGeometry(QtCore.QRect(380, 370, 31, 31))
        self.tile17.setText("")
        self.tile17.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile17.setScaledContents(True)
        self.tile17.setObjectName("tile17")
        self.start = QtWidgets.QLabel(self.gamePage)
        self.start.setGeometry(QtCore.QRect(740, 520, 61, 31))
        self.start.setText("")
        self.start.setPixmap(QtGui.QPixmap("start_tile.png"))
        self.start.setScaledContents(True)
        self.start.setObjectName("start")
        self.tile11 = QtWidgets.QLabel(self.gamePage)
        self.tile11.setGeometry(QtCore.QRect(410, 520, 31, 31))
        self.tile11.setText("")
        self.tile11.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile11.setScaledContents(True)
        self.tile11.setObjectName("tile11")
        self.tile13 = QtWidgets.QLabel(self.gamePage)
        self.tile13.setGeometry(QtCore.QRect(380, 490, 31, 31))
        self.tile13.setText("")
        self.tile13.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile13.setScaledContents(True)
        self.tile13.setObjectName("tile13")
        self.tile15 = QtWidgets.QLabel(self.gamePage)
        self.tile15.setGeometry(QtCore.QRect(380, 430, 31, 31))
        self.tile15.setText("")
        self.tile15.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile15.setScaledContents(True)
        self.tile15.setObjectName("tile15")
        self.tile21 = QtWidgets.QLabel(self.gamePage)
        self.tile21.setGeometry(QtCore.QRect(380, 250, 31, 31))
        self.tile21.setText("")
        self.tile21.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile21.setScaledContents(True)
        self.tile21.setObjectName("tile21")
        self.tile12 = QtWidgets.QLabel(self.gamePage)
        self.tile12.setGeometry(QtCore.QRect(380, 520, 31, 31))
        self.tile12.setText("")
        self.tile12.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile12.setScaledContents(True)
        self.tile12.setObjectName("tile12")
        self.Reminder = QtWidgets.QLabel(self.gamePage)
        self.Reminder.setGeometry(QtCore.QRect(420, 329, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.Reminder.setFont(font)
        self.Reminder.setAlignment(QtCore.Qt.AlignCenter)
        self.Reminder.setObjectName("Reminder")
        self.tile9 = QtWidgets.QLabel(self.gamePage)
        self.tile9.setGeometry(QtCore.QRect(470, 520, 31, 31))
        self.tile9.setText("")
        self.tile9.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile9.setScaledContents(True)
        self.tile9.setObjectName("tile9")
        self.banner9 = QtWidgets.QLabel(self.gamePage)
        self.banner9.setGeometry(QtCore.QRect(40, 10, 471, 121))
        self.banner9.setText("")
        self.banner9.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner9.setScaledContents(True)
        self.banner9.setObjectName("banner9")
        self.tile23 = QtWidgets.QLabel(self.gamePage)
        self.tile23.setGeometry(QtCore.QRect(380, 190, 31, 31))
        self.tile23.setText("")
        self.tile23.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile23.setScaledContents(True)
        self.tile23.setObjectName("tile23")
        self.tile41 = QtWidgets.QLabel(self.gamePage)
        self.tile41.setGeometry(QtCore.QRect(770, 280, 31, 31))
        self.tile41.setText("")
        self.tile41.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile41.setScaledContents(True)
        self.tile41.setObjectName("tile41")
        self.tile8 = QtWidgets.QLabel(self.gamePage)
        self.tile8.setGeometry(QtCore.QRect(500, 520, 31, 31))
        self.tile8.setText("")
        self.tile8.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile8.setScaledContents(True)
        self.tile8.setObjectName("tile8")
        self.tile34 = QtWidgets.QLabel(self.gamePage)
        self.tile34.setGeometry(QtCore.QRect(680, 160, 31, 31))
        self.tile34.setText("")
        self.tile34.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile34.setScaledContents(True)
        self.tile34.setObjectName("tile34")
        self.tile14 = QtWidgets.QLabel(self.gamePage)
        self.tile14.setGeometry(QtCore.QRect(380, 460, 31, 31))
        self.tile14.setText("")
        self.tile14.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile14.setScaledContents(True)
        self.tile14.setObjectName("tile14")
        self.tile45 = QtWidgets.QLabel(self.gamePage)
        self.tile45.setGeometry(QtCore.QRect(770, 400, 31, 31))
        self.tile45.setText("")
        self.tile45.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile45.setScaledContents(True)
        self.tile45.setObjectName("tile45")
        self.tile5 = QtWidgets.QLabel(self.gamePage)
        self.tile5.setGeometry(QtCore.QRect(590, 520, 31, 31))
        self.tile5.setText("")
        self.tile5.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile5.setScaledContents(True)
        self.tile5.setObjectName("tile5")
        self.tile43 = QtWidgets.QLabel(self.gamePage)
        self.tile43.setGeometry(QtCore.QRect(770, 340, 31, 31))
        self.tile43.setText("")
        self.tile43.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile43.setScaledContents(True)
        self.tile43.setObjectName("tile43")
        self.tile44 = QtWidgets.QLabel(self.gamePage)
        self.tile44.setGeometry(QtCore.QRect(770, 370, 31, 31))
        self.tile44.setText("")
        self.tile44.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile44.setScaledContents(True)
        self.tile44.setObjectName("tile44")
        self.tile24 = QtWidgets.QLabel(self.gamePage)
        self.tile24.setGeometry(QtCore.QRect(380, 160, 31, 31))
        self.tile24.setText("")
        self.tile24.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile24.setScaledContents(True)
        self.tile24.setObjectName("tile24")
        self.tile32 = QtWidgets.QLabel(self.gamePage)
        self.tile32.setGeometry(QtCore.QRect(620, 160, 31, 31))
        self.tile32.setText("")
        self.tile32.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile32.setScaledContents(True)
        self.tile32.setObjectName("tile32")
        self.tile42 = QtWidgets.QLabel(self.gamePage)
        self.tile42.setGeometry(QtCore.QRect(770, 310, 31, 31))
        self.tile42.setText("")
        self.tile42.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile42.setScaledContents(True)
        self.tile42.setObjectName("tile42")
        self.tile37 = QtWidgets.QLabel(self.gamePage)
        self.tile37.setGeometry(QtCore.QRect(770, 160, 31, 31))
        self.tile37.setText("")
        self.tile37.setPixmap(QtGui.QPixmap("event tile.png"))
        self.tile37.setScaledContents(True)
        self.tile37.setObjectName("tile37")
        self.tile10 = QtWidgets.QLabel(self.gamePage)
        self.tile10.setGeometry(QtCore.QRect(440, 520, 31, 31))
        self.tile10.setText("")
        self.tile10.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile10.setScaledContents(True)
        self.tile10.setObjectName("tile10")
        self.tile31 = QtWidgets.QLabel(self.gamePage)
        self.tile31.setGeometry(QtCore.QRect(590, 160, 31, 31))
        self.tile31.setText("")
        self.tile31.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile31.setScaledContents(True)
        self.tile31.setObjectName("tile31")
        self.tile7 = QtWidgets.QLabel(self.gamePage)
        self.tile7.setGeometry(QtCore.QRect(530, 520, 31, 31))
        self.tile7.setText("")
        self.tile7.setPixmap(QtGui.QPixmap("event tile.png"))
        self.tile7.setScaledContents(True)
        self.tile7.setObjectName("tile7")
        self.tile3 = QtWidgets.QLabel(self.gamePage)
        self.tile3.setGeometry(QtCore.QRect(650, 520, 31, 31))
        self.tile3.setText("")
        self.tile3.setPixmap(QtGui.QPixmap("event tile.png"))
        self.tile3.setScaledContents(True)
        self.tile3.setObjectName("tile3")
        self.tile2 = QtWidgets.QLabel(self.gamePage)
        self.tile2.setGeometry(QtCore.QRect(680, 520, 31, 31))
        self.tile2.setText("")
        self.tile2.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile2.setScaledContents(True)
        self.tile2.setObjectName("tile2")
        self.tile48 = QtWidgets.QLabel(self.gamePage)
        self.tile48.setGeometry(QtCore.QRect(770, 490, 31, 31))
        self.tile48.setText("")
        self.tile48.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile48.setScaledContents(True)
        self.tile48.setObjectName("tile48")
        self.tile39 = QtWidgets.QLabel(self.gamePage)
        self.tile39.setGeometry(QtCore.QRect(770, 220, 31, 31))
        self.tile39.setText("")
        self.tile39.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile39.setScaledContents(True)
        self.tile39.setObjectName("tile39")
        self.startCard = QtWidgets.QPushButton(self.gamePage)
        self.startCard.setGeometry(QtCore.QRect(420, 200, 111, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.startCard.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.startCard.setFont(font)
        self.startCard.setAutoFillBackground(False)
        self.startCard.setStyleSheet("#startCard {\n"
"background-color: rgb(32, 198, 255)\n"
"}")
        self.startCard.setObjectName("startCard")
        self.eventCard = QtWidgets.QPushButton(self.gamePage)
        self.eventCard.setGeometry(QtCore.QRect(420, 440, 111, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(43, 198, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 198, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 198, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 198, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 198, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 198, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 198, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 198, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(43, 198, 43))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.eventCard.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.eventCard.setFont(font)
        self.eventCard.setAutoFillBackground(False)
        self.eventCard.setStyleSheet("#eventCard {\n"
"background-color: rgb(43, 198, 43)\n"
"}")
        self.eventCard.setObjectName("eventCard")
        self.tile36 = QtWidgets.QLabel(self.gamePage)
        self.tile36.setGeometry(QtCore.QRect(740, 160, 31, 31))
        self.tile36.setText("")
        self.tile36.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile36.setScaledContents(True)
        self.tile36.setObjectName("tile36")
        self.tile40 = QtWidgets.QLabel(self.gamePage)
        self.tile40.setGeometry(QtCore.QRect(770, 250, 31, 31))
        self.tile40.setText("")
        self.tile40.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile40.setScaledContents(True)
        self.tile40.setObjectName("tile40")
        self.tile46 = QtWidgets.QLabel(self.gamePage)
        self.tile46.setGeometry(QtCore.QRect(770, 430, 31, 31))
        self.tile46.setText("")
        self.tile46.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile46.setScaledContents(True)
        self.tile46.setObjectName("tile46")
        self.tile16 = QtWidgets.QLabel(self.gamePage)
        self.tile16.setGeometry(QtCore.QRect(380, 400, 31, 31))
        self.tile16.setText("")
        self.tile16.setPixmap(QtGui.QPixmap("event tile.png"))
        self.tile16.setScaledContents(True)
        self.tile16.setObjectName("tile16")
        self.tile28 = QtWidgets.QLabel(self.gamePage)
        self.tile28.setGeometry(QtCore.QRect(500, 160, 31, 31))
        self.tile28.setText("")
        self.tile28.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile28.setScaledContents(True)
        self.tile28.setObjectName("tile28")
        self.tile38 = QtWidgets.QLabel(self.gamePage)
        self.tile38.setGeometry(QtCore.QRect(770, 190, 31, 31))
        self.tile38.setText("")
        self.tile38.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile38.setScaledContents(True)
        self.tile38.setObjectName("tile38")
        self.tile6 = QtWidgets.QLabel(self.gamePage)
        self.tile6.setGeometry(QtCore.QRect(560, 520, 31, 31))
        self.tile6.setText("")
        self.tile6.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile6.setScaledContents(True)
        self.tile6.setObjectName("tile6")
        self.tile29 = QtWidgets.QLabel(self.gamePage)
        self.tile29.setGeometry(QtCore.QRect(530, 160, 31, 31))
        self.tile29.setText("")
        self.tile29.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile29.setScaledContents(True)
        self.tile29.setObjectName("tile29")
        self.tile19 = QtWidgets.QLabel(self.gamePage)
        self.tile19.setGeometry(QtCore.QRect(380, 310, 31, 31))
        self.tile19.setText("")
        self.tile19.setPixmap(QtGui.QPixmap("white_tile.bmp"))
        self.tile19.setScaledContents(True)
        self.tile19.setObjectName("tile19")
        self.startTasks = QtWidgets.QStackedWidget(self.gamePage)
        self.startTasks.setGeometry(QtCore.QRect(40, 160, 291, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 198, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.startTasks.setPalette(palette)
        self.startTasks.setAutoFillBackground(True)
        self.startTasks.setObjectName("startTasks")
        self.Task1 = QtWidgets.QWidget()
        self.Task1.setObjectName("Task1")
        self.Task1Txt = QtWidgets.QTextEdit(self.Task1)
        self.Task1Txt.setGeometry(QtCore.QRect(10, 10, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.Task1Txt.setFont(font)
        self.Task1Txt.setStyleSheet("#Task1Txt {\n"
"background-color: rgb(32, 198, 255)\n"
"}")
        self.Task1Txt.setObjectName("Task1Txt")
        self.nextTaskBtn = QtWidgets.QPushButton(self.Task1)
        self.nextTaskBtn.setGeometry(QtCore.QRect(220, 160, 61, 32))
        self.nextTaskBtn.setObjectName("nextTaskBtn")
        self.startTasks.addWidget(self.Task1)
        self.Task2 = QtWidgets.QWidget()
        self.Task2.setObjectName("Task2")
        self.OKTaskBtn = QtWidgets.QPushButton(self.Task2)
        self.OKTaskBtn.setGeometry(QtCore.QRect(220, 160, 61, 32))
        self.OKTaskBtn.setObjectName("OKTaskBtn")
        self.Task2Txt = QtWidgets.QTextEdit(self.Task2)
        self.Task2Txt.setGeometry(QtCore.QRect(10, 10, 271, 81))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.Task2Txt.setFont(font)
        self.Task2Txt.setStyleSheet("#Task2Txt {\n"
"background-color: rgb(32, 198, 255)\n"
"}")
        self.Task2Txt.setObjectName("Task2Txt")
        self.backBtn = QtWidgets.QPushButton(self.Task2)
        self.backBtn.setGeometry(QtCore.QRect(160, 160, 61, 32))
        self.backBtn.setObjectName("backBtn")
        self.startTaskError = QtWidgets.QLabel(self.Task2)
        self.startTaskError.setGeometry(QtCore.QRect(29, 120, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(12)
        self.startTaskError.setFont(font)
        self.startTaskError.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startTaskError.setObjectName("startTaskError")
        self.startTasks.addWidget(self.Task2)
        self.debriefBtn = QtWidgets.QPushButton(self.gamePage)
        self.debriefBtn.setGeometry(QtCore.QRect(500, 380, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        font.setPointSize(18)
        self.debriefBtn.setFont(font)
        self.debriefBtn.setObjectName("debriefBtn")
        self.Event = QtWidgets.QFrame(self.gamePage)
        self.Event.setGeometry(QtCore.QRect(200, 560, 671, 441))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.Event.setFont(font)
        self.Event.setStyleSheet("#Event {\n"
"background-color: rgb(34, 222, 23)\n"
"}")
        self.Event.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Event.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Event.setObjectName("Event")
        self.eventTxt = QtWidgets.QLabel(self.Event)
        self.eventTxt.setGeometry(QtCore.QRect(50, 50, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.eventTxt.setFont(font)
        self.eventTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.eventTxt.setObjectName("eventTxt")
        self.eventPic = QtWidgets.QLabel(self.Event)
        self.eventPic.setGeometry(QtCore.QRect(210, 100, 191, 141))
        self.eventPic.setText("")
        self.eventPic.setPixmap(QtGui.QPixmap("breakfast1.jpeg"))
        self.eventPic.setScaledContents(True)
        self.eventPic.setObjectName("eventPic")
        self.eventTask = QtWidgets.QPushButton(self.Event)
        self.eventTask.setGeometry(QtCore.QRect(540, 10, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 143, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.eventTask.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.eventTask.setFont(font)
        self.eventTask.setAutoFillBackground(False)
        self.eventTask.setStyleSheet("#eventTask {\n"
"background-color: rgb(191, 143, 255)\n"
"}")
        self.eventTask.setObjectName("eventTask")
        self.eventOK = QtWidgets.QPushButton(self.Event)
        self.eventOK.setGeometry(QtCore.QRect(540, 400, 113, 32))
        self.eventOK.setObjectName("eventOK")
        self.eventError = QtWidgets.QLabel(self.Event)
        self.eventError.setGeometry(QtCore.QRect(190, 370, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.eventError.setFont(font)
        self.eventError.setObjectName("eventError")
        self.option1 = QtWidgets.QRadioButton(self.Event)
        self.option1.setGeometry(QtCore.QRect(200, 260, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.option1.setFont(font)
        self.option1.setObjectName("option1")
        self.option2 = QtWidgets.QRadioButton(self.Event)
        self.option2.setGeometry(QtCore.QRect(200, 290, 331, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.option2.setFont(font)
        self.option2.setObjectName("option2")
        self.option3 = QtWidgets.QRadioButton(self.Event)
        self.option3.setGeometry(QtCore.QRect(200, 320, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Geneva")
        self.option3.setFont(font)
        self.option3.setObjectName("option3")
        self.taskWindow = QtWidgets.QFrame(self.gamePage)
        self.taskWindow.setGeometry(QtCore.QRect(830, 160, 401, 371))
        self.taskWindow.setStyleSheet("#taskWindow {\n"
"background-color: rgb(220, 130, 242)\n"
"}")
        self.taskWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.taskWindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.taskWindow.setObjectName("taskWindow")
        self.antibioTask = QtWidgets.QPushButton(self.taskWindow)
        self.antibioTask.setGeometry(QtCore.QRect(32, 50, 341, 32))
        self.antibioTask.setObjectName("antibioTask")
        self.momTask = QtWidgets.QPushButton(self.taskWindow)
        self.momTask.setGeometry(QtCore.QRect(30, 90, 341, 32))
        self.momTask.setObjectName("momTask")
        self.essayTask = QtWidgets.QPushButton(self.taskWindow)
        self.essayTask.setGeometry(QtCore.QRect(30, 130, 341, 32))
        self.essayTask.setObjectName("essayTask")
        self.bookTask = QtWidgets.QPushButton(self.taskWindow)
        self.bookTask.setGeometry(QtCore.QRect(30, 170, 341, 32))
        self.bookTask.setObjectName("bookTask")
        self.medicineTask = QtWidgets.QPushButton(self.taskWindow)
        self.medicineTask.setGeometry(QtCore.QRect(30, 210, 341, 32))
        self.medicineTask.setObjectName("medicineTask")
        self.cancelTask = QtWidgets.QPushButton(self.taskWindow)
        self.cancelTask.setGeometry(QtCore.QRect(130, 320, 151, 32))
        self.cancelTask.setObjectName("cancelTask")
        self.lectureTask = QtWidgets.QPushButton(self.taskWindow)
        self.lectureTask.setGeometry(QtCore.QRect(30, 250, 341, 32))
        self.lectureTask.setObjectName("lectureTask")
        self.VirtualDayExp.addWidget(self.gamePage)
        self.catPage = QtWidgets.QWidget()
        self.catPage.setObjectName("catPage")
        self.banner11 = QtWidgets.QLabel(self.catPage)
        self.banner11.setGeometry(QtCore.QRect(40, 10, 471, 121))
        self.banner11.setText("")
        self.banner11.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner11.setScaledContents(True)
        self.banner11.setObjectName("banner11")
        self.banner12 = QtWidgets.QLabel(self.catPage)
        self.banner12.setGeometry(QtCore.QRect(510, 10, 451, 121))
        self.banner12.setText("")
        self.banner12.setPixmap(QtGui.QPixmap("UCL-Logo-Black.jpg"))
        self.banner12.setObjectName("banner12")
        self.VirtualDayExp.addWidget(self.catPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.startTasks.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.consentHeader.setText(_translate("MainWindow", "EXPERIMENTAL CONSENT"))
        self.errorConsent.setText(_translate("MainWindow", "PLEASE CONFIRM YOUR CONSENT TO PARTICIPATE IN THIS EXPERIMENT"))
        self.consentBody.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Geneva\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\';\">I understand that by checking the below box I agree to participate in this experiment and have my age, gender, height, weight, and alcohol use habits collected and used as data. I understand that this data will be used anonymously.</span></p></body></html>"))
        self.directions.setText(_translate("MainWindow", "EXPERIMENTER: Please enter participant ID"))
        self.submitConsent.setText(_translate("MainWindow", "NEXT"))
        self.consentBox.setText(_translate("MainWindow", "I CONSENT TO PARTICIPATE IN THIS EXPERIMENT"))
        self.genderLabel.setText(_translate("MainWindow", "GENDER"))
        self.submitButton.setText(_translate("MainWindow", "NEXT"))
        self.errorAge.setText(_translate("MainWindow", "YOU MUST BE 18 OR OVER TO PARTICIPATE"))
        self.Male.setText(_translate("MainWindow", "M"))
        self.Female.setText(_translate("MainWindow", "F"))
        self.Other.setText(_translate("MainWindow", "O"))
        self.demoHeader.setText(_translate("MainWindow", "DEMOGRAPHIC INFO"))
        self.errorDemo.setText(_translate("MainWindow", "PLEASE COMPLETE ALL FIELDS"))
        self.heightLabel.setText(_translate("MainWindow", "HEIGHT (IN)"))
        self.ageLabel.setText(_translate("MainWindow", "AGE"))
        self.weightLabel.setText(_translate("MainWindow", "WEIGHT (LBS)"))
        self.CAGEdir_5.setText(_translate("MainWindow", "Have you ever felt the need to drink first thing in the morning to steady your nerves or to get rid of a hangover?"))
        self.CAGEdir_2.setText(_translate("MainWindow", "Have you ever felt you needed to cut down on your drinking?"))
        self.submitButton_2.setText(_translate("MainWindow", "NEXT"))
        self.CAGEdir.setText(_translate("MainWindow", "Please answer the following questions as honestly as you can."))
        self.Y3.setText(_translate("MainWindow", "Yes"))
        self.N3.setText(_translate("MainWindow", "No"))
        self.CAGEHeader.setText(_translate("MainWindow", "CAGE Questionnaire"))
        self.errorCAGE.setText(_translate("MainWindow", "PLEASE COMPLETE ALL FIELDS"))
        self.CAGEdir_3.setText(_translate("MainWindow", "Have people annoyed you by criticizing your drinking?"))
        self.Y1.setText(_translate("MainWindow", "Yes"))
        self.N1.setText(_translate("MainWindow", "No"))
        self.Y2.setText(_translate("MainWindow", "Yes"))
        self.N2.setText(_translate("MainWindow", "No"))
        self.CAGEdir_4.setText(_translate("MainWindow", "Have you ever felt guilty about drinking?"))
        self.Y4.setText(_translate("MainWindow", "Yes"))
        self.N4.setText(_translate("MainWindow", "No"))
        self.InstructionsHeader.setText(_translate("MainWindow", "VIRTUAL DAY Instructions"))
        self.OKButton.setText(_translate("MainWindow", "OK"))
        self.label.setText(_translate("MainWindow", "In the following game, you will be simulating a normal day with each cycle around the board. Each tile represents 20 minutes of your day, and each day begins at 8AM and ends at midnight.\n"
"\n"
"Please follow the instructions prompt in the centre of the board.\n"
"\n"
"To advance your piece you must click on it, and it will automatically advance the number shown on the die.\n"
"\n"
"When you pass green E tiles, you must click to pick up an Event Card. Event Cards contain regular daily events such as meals, shopping, and going to work or school. In each card, you will need to select from a few choices such as what to eat, buy, etc. \n"
"\n"
"At the start of the game, you will need to pick up a Start Card, which contains tasks that you need to remember to execute. These tasks will need to be performed either at a certain time of day, or at a specific event during that day. You will be required to read each task on the Start Card out loud, twice. Once you set down the Start Card you will not be able to see your tasks again.\n"
"\n"
"For time-based tasks, click “Perform Task” button at the top right of the screen immediately after passing the tile corresponding to that time.\n"
"\n"
"For event-based tasks, click the “Perform Task” button within the event card."))
        self.Timer.setText(_translate("MainWindow", "08:00"))
        self.performTask.setText(_translate("MainWindow", "PERFORM TASK"))
        self.Reminder.setText(_translate("MainWindow", "Pick up a Start Card before continuing"))
        self.startCard.setText(_translate("MainWindow", "START CARD"))
        self.eventCard.setText(_translate("MainWindow", "EVENT CARD"))
        self.Task1Txt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Geneva\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\';\">TASK 2:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\';\">Drop in the dry cleaning when you go out shopping</span></p></body></html>"))
        self.nextTaskBtn.setText(_translate("MainWindow", "NEXT"))
        self.OKTaskBtn.setText(_translate("MainWindow", "OK"))
        self.Task2Txt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Geneva\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\';\">TASK 2:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'.SF NS Text\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.SF NS Text\';\">Drop in the dry cleaning when you go out shopping</span></p></body></html>"))
        self.backBtn.setText(_translate("MainWindow", "BACK"))
        self.startTaskError.setText(_translate("MainWindow", "Please read task instructions\n"
" at least twice"))
        self.debriefBtn.setText(_translate("MainWindow", "CONTINUE"))
        self.eventTxt.setText(_translate("MainWindow", "You are having breakfast. What do you eat?"))
        self.eventTask.setText(_translate("MainWindow", "PERFORM TASK"))
        self.eventOK.setText(_translate("MainWindow", "OK"))
        self.eventError.setText(_translate("MainWindow", "Please select an option before continuing"))
        self.option1.setText(_translate("MainWindow", "Eggs and toast"))
        self.option2.setText(_translate("MainWindow", "Fruit and coffee"))
        self.option3.setText(_translate("MainWindow", "Cappuccino and a pastry"))
        self.antibioTask.setText(_translate("MainWindow", "take antibiotics"))
        self.momTask.setText(_translate("MainWindow", "mail a birthday card for your mom"))
        self.essayTask.setText(_translate("MainWindow", "submit an essay"))
        self.bookTask.setText(_translate("MainWindow", "return library book"))
        self.medicineTask.setText(_translate("MainWindow", "take cold medicine"))
        self.cancelTask.setText(_translate("MainWindow", "CANCEL"))
        self.lectureTask.setText(_translate("MainWindow", "attend lecture"))

